name: shiga_native
description: Shiga client for native android and ios app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  cloud_functions: ^3.0.3
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.1.0
  permission_handler: ^8.1.6
  geolocator: ^7.6.2
  json_annotation: ^4.1.0
  provider: ^6.0.0
  flutter_settings_ui: ^2.0.1
  qr_flutter: ^4.0.0
  ionicons: ^0.1.2
  qr_code_scanner: ^0.6.0
  mapbox_gl: ^0.14.0
  sliding_up_panel: ^2.0.0+1
  geohashlib:
    path: ./packages/geohashlib
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  build_runner: ^2.1.2
flutter:
  uses-material-design: false
  fonts:
    - family: RockSalt
      fonts:
        - asset: assets/font/RockSalt-Regular.ttf
    - family: OdibeeSans
      fonts:
        - asset: assets/font/OdibeeSans-Regular.ttf
    - family: Sniglet
      fonts:
        - asset: assets/font/Sniglet-Regular.ttf
        - asset: assets/font/Sniglet-ExtraBold.ttf
  assets:
    - assets/img/
    - assets/font/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
